### Quiz

#### Part 1

Read in the data found in `diamonds.csv` and then print a summary of the DataFrame that shows column names, non-null counts, and data types.

In [28]:
import pandas as pd

df = pd.read_csv("../data/diamonds.csv")
df.describe()

,carat,depth,table,x,y,z,price
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,5.731157,5.734526,3.538734,3932.799722
std,0.474011,1.432621,2.234491,1.121761,1.142135,0.705699,3989.439738
min,0.200000,43.000000,43.000000,0.000000,0.000000,0.000000,326.000000
25%,0.400000,61.000000,56.000000,4.710000,4.720000,2.910000,950.000000
50%,0.700000,61.800000,57.000000,5.700000,5.710000,3.530000,2401.000000
75%,1.040000,62.500000,59.000000,6.540000,6.540000,4.040000,5324.250000
max,5.010000,79.000000,95.000000,10.740000,58.900000,31.800000,18823.000000

#### Part 2

Select only the price and carat columns from the DataFrame.

In [29]:
df[["price", "carat"]]

       price  carat
0        326   0.23
1        326   0.21
2        327   0.23
3        334   0.29
4        335   0.31
...      ...    ...
53935   2757   0.72
53936   2757   0.72
53937   2757   0.70
53938   2757   0.86
53939   2757   0.75

[53940 rows x 2 columns]

#### Part 3

Create a new column called `box_volume` that is the product of dimensions `x`, `y`, and `z`. Then display the new DataFrame.

In [36]:
df["box_volume"] = df["x"] * df["y"] * df["z"]
df

,carat,cut,color,clarity,depth,table,x,y,z,price,box_volume,good_deal
0,0.23,Ideal,E,SI2,61.5,55.0,3.95,3.98,2.43,326,38.202030,1
1,0.21,Premium,E,SI1,59.8,61.0,3.89,3.84,2.31,326,34.505856,0
2,0.23,Good,E,VS1,56.9,65.0,4.05,4.07,2.31,327,38.076885,0
3,0.29,Premium,I,VS2,62.4,58.0,4.20,4.23,2.63,334,46.724580,0
4,0.31,Good,J,SI2,63.3,58.0,4.34,4.35,2.75,335,51.917250,0
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,5.75,5.76,3.50,2757,115.920000,0
53936,0.72,Good,D,SI1,63.1,55.0,5.69,5.75,3.61,2757,118.110175,0
53937,0.70,Very Good,D,SI1,62.8,60.0,5.66,5.68,3.56,2757,114.449728,0
53938,0.86,Premium,H,SI2,61.0,58.0,6.15,6.12,3.74,2757,140.766120,0
53939,0.75,Ideal,D,SI2,62.2,55.0,5.83,5.87,3.64,2757,124.568444,0

#### Part 4

Use either `map` or `apply` (whichever is more appropriate) to create a new column called `good_deal` which is 1 if the cut is Ideal and the price is below 500. Then display the new DataFrame.

In [35]:
df["good_deal"] = df.apply(
    lambda row: 1 if (row["cut"] == "Ideal" and row["price"] < 500 )
                    else 0, axis=1
)
df

,carat,cut,color,clarity,depth,table,x,y,z,price,box_volume,good_deal
0,0.23,Ideal,E,SI2,61.5,55.0,3.95,3.98,2.43,326,38.202030,1
1,0.21,Premium,E,SI1,59.8,61.0,3.89,3.84,2.31,326,34.505856,0
2,0.23,Good,E,VS1,56.9,65.0,4.05,4.07,2.31,327,38.076885,0
3,0.29,Premium,I,VS2,62.4,58.0,4.20,4.23,2.63,334,46.724580,0
4,0.31,Good,J,SI2,63.3,58.0,4.34,4.35,2.75,335,51.917250,0
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,5.75,5.76,3.50,2757,115.920000,0
53936,0.72,Good,D,SI1,63.1,55.0,5.69,5.75,3.61,2757,118.110175,0
53937,0.70,Very Good,D,SI1,62.8,60.0,5.66,5.68,3.56,2757,114.449728,0
53938,0.86,Premium,H,SI2,61.0,58.0,6.15,6.12,3.74,2757,140.766120,0
53939,0.75,Ideal,D,SI2,62.2,55.0,5.83,5.87,3.64,2757,124.568444,0

#### Part 5

Find and output the maximum carat value for each color.

In [18]:
df.groupby("color")["carat"].max()

color
D    3.40
E    3.05
F    3.01
G    3.01
H    4.13
I    4.01
J    5.01
Name: carat, dtype: float64

#### Part 6

Merge the `movies` and `ratings` DataFrames so that all information about the movies in `movies` is kept even if information about their rating is not available in `ratings`. Display the merged DataFrame.

In [20]:
movies = pd.DataFrame({
    "movie_id": [10, 11, 12, 13],
    "title": ["Inception", "Titanic", "Avatar", "Jaws"]
})

ratings = pd.DataFrame({
    "movie_id": [10, 11, 14],
    "rating": [8.8, 7.8, 6.5]
})

In [21]:
movies.merge(ratings, on="movie_id", how="left")

   movie_id      title  rating
0        10  Inception     8.8
1        11    Titanic     7.8
2        12     Avatar     NaN
3        13       Jaws     NaN