### Practice Quiz

#### Part 1

Read in the dataset in `math_education.csv` and display the first 5 rows of the dataset.

In [21]:
import pandas as pd
df = pd.read_csv("../data/math_education.csv")
df.head()

,course,learning_style,study_hours,problems_completed,time_per_problem,test_score
0,Algebra,Visual,3.006302,8,4.47022107312782 minutes,64.21507328
1,Precalculus,Auditory,3.420090,15,4.71498034871565 minutes,40.95722105
2,Geometry,Visual,4.973030,17,2.48529359046541 minutes,68.68881949
3,Calculus,Kinesthetic,6.669562,42,2.59407872904447 minutes,53.83409822
4,Calculus,Kinesthetic,0.626643,16,4.58399380648794 minutes,33.88539529

#### Part 2

Drop any duplicate rows (rows where every value is the same).

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   course              1050 non-null   object
 1   learning_style      1050 non-null   object
 2   study_hours         1018 non-null   float64
 3   problems_completed  1050 non-null   int64
 4   time_per_problem    1050 non-null   object
 5   test_score          1050 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 49.3+ KB

In [23]:
df.drop_duplicates(inplace=True)
df

,course,learning_style,study_hours,problems_completed,time_per_problem,test_score
0,Algebra,Visual,3.006302,8,4.47022107312782 minutes,64.21507328
1,Precalculus,Auditory,3.420090,15,4.71498034871565 minutes,40.95722105
2,Geometry,Visual,4.973030,17,2.48529359046541 minutes,68.68881949
3,Calculus,Kinesthetic,6.669562,42,2.59407872904447 minutes,53.83409822
4,Calculus,Kinesthetic,0.626643,16,4.58399380648794 minutes,33.88539529
...,...,...,...,...,...,...
1043,Geometry,Auditory,4.870199,10,3.39129767272943 minutes,52.41720566
1045,Statistics,Auditory,8.998495,23,3.75381151051312 minutes,71.19203878
1046,Geometry,visual,4.891270,21,2.56712733990959 minutes,63 percent
1047,Precalculus,Visual,5.749600,13,4.95205265475675 minutes,57.60622049
1048,Calculus,Visual,10.295853,48,2.69373174418924 minutes,79.38736348

#### Part 3

Treat any missing values for `study_hours` by replacing them with the median of `study_hours`.

In [32]:
df["study_hours"] = df["study_hours"].fillna(df["study_hours"].median())
df["study_hours"].describe()

count    1021.000000
mean        5.215174
std         2.160132
min         0.500000
25%         3.637288
50%         4.989688
75%         6.433367
max        16.226294
Name: study_hours, dtype: float64

#### Part 4

Do the following with the `time_per_problem` variable:

- Clean up the text
- Convert to `float`
- Convert to everything to seconds

In [35]:
MIN_TO_SEC = 60

time_multiplier = df["time_per_problem"].str.contains("minutes").map(
    lambda x: MIN_TO_SEC if x else 1
)

df["time_per_problem"] = df["time_per_problem"].str.replace("minutes", "").str.replace("seconds", "").astype("float")*time_multiplier


df["time_per_problem"].describe()

count    1021.000000
mean      223.743169
std       108.534540
min        48.061526
25%       148.779657
50%       203.211454
75%       271.352660
max      1113.681145
Name: time_per_problem, dtype: float64

#### Part 5

Remove any unwanted text ("%" and "percent") from the `test_score` variable and then convert this to a `float`.

In [38]:
df["test_score"] = df["test_score"].str.replace("%", "").str.replace("percent", "").astype("float")

df["test_score"].describe()

count    1021.000000
mean       59.055039
std        13.136104
min         0.000000
25%        51.287212
50%        59.870238
75%        67.395828
max        97.562237
Name: test_score, dtype: float64

#### Part 6

Standardize the categories in `learning_style` using the following mapping:

- Audio, auditory, AUDITORY, Auditory → Auditory
- kinesthetic, KINESTHETIC, Kinesthetic (with space), Kinesthetic → Kinesthetic
- visual, VISUAL, Visual → Visual

(Note that one of the values for the Kinesthetic category has one extra space that needs to be removed)

In [39]:
df["learning_style"].unique()

array(['Visual', 'Auditory', 'Kinesthetic', 'auditory', 'VISUAL',
       'visual', 'KINESTHETIC', 'Audio', 'Kinesthetic ', 'AUDITORY ',
       'kinesthetic'], dtype=object)

In [40]:
df["learning_style"] = df["learning_style"].str.replace(" ", "")

In [41]:
df["learning_style"].unique()

array(['Visual', 'Auditory', 'Kinesthetic', 'auditory', 'VISUAL',
       'visual', 'KINESTHETIC', 'Audio', 'AUDITORY', 'kinesthetic'],
      dtype=object)

In [43]:
learning_dict = {}

learning_dict["Audio"] = "Auditory"
learning_dict["auditory"] = "Auditory"
learning_dict["AUDITORY,"] = "Auditory"
learning_dict["Auditory"] = "Auditory"

learning_dict["kinesthetic"] = "Kinesthetic"
learning_dict["KINESTHETIC,"] = "Kinesthetic"
learning_dict["Kinesthetic"] = "Kinesthetic"

learning_dict["visual"] = "Visual"
learning_dict["VISUAL"] = "Visual"
learning_dict["Visual"] = "Visual"


df["learning_style"] = df["learning_style"].map(learning_dict)

df["learning_style"].describe()

count       1010
unique         3
top       Visual
freq         510
Name: learning_style, dtype: object

In [44]:
df["learning_style"].unique()

array(['Visual', 'Auditory', 'Kinesthetic', nan], dtype=object)