I would keep the below 19 variables because it includes useful variables like address, amenities, the house size , their bedrroms numbers and the conditions of the houses which are important in predicting the house price.

1. **FireplaceY/N** -  1 value missing. deleting using case deletion, since it is negligible. Binary encode to 0's and 1's
2. **Structure Type** - 1 value missing. deleting using case deletion
3. **View Y/N** - missing 3030 data values, which is more than a half, will impute "Unknown" because it influences strongly the house price.  encode to 0, 1 and 2.
4. **Total bedrooms** - None
5. **Total parking** - 11 missing values, safe to delete using case deletion since the percentage is very small.
6. **New construction** 33 missing values, delete using case deletion out of the 4500 values. 
7. **Property Condition** 2160 missing values, impute with "Unkown" since property condition affects price
8. **Virtual Tour** - 2856 misisng values, binary encode 'click here' to 1 and missing to 0.
9. **Latitude** - None
10. **Longitude** - None
11. **Air Conditioning(Y/N)** - 1 missing, case deletion, binary encode to 0 and 1
12. **heatingY/N** - 1 missing, case deletion, binary encode to 0 and 1
13. **High School District** - 86 missing values, listwise deletion since it is small percentage of data missing.
14. **Year Built** - None
15. **Total Baths** - None
16. **lot_size** - None  - remove Acres. convert to float
17. **house_size** - None - remove SQFT text, comvert to float
18. **Waterfront Y/N** - 120 missing, case deletion since it is small percentage. binary encode to 0 and 1
19. **Carport Y/N** - None
20. **Senior Community Y/N** - 1 missing, case deletion. binary encode to 0 and 1

In [478]:
import pandas as pd
df = pd.read_csv("../data/tacoma_houses.csv", low_memory = False)

selected_columns = [
    "Fireplace Y/N", 
    "Structure Type", 
    "Total Parking", 
    "New Construction", 
    "Air Conditioning Y/N",
    "Heating Y/N",
    "High School District",
    "Waterfront Y/N",
    "Senior Community Y/N",
    "Virtual Tour",
    "Carport Y/N",
    "house_size", 
    "lot_size",
    "Year Built",
    "Total Baths",
    "Longitude", 
    "Latitude",
    "Property Condition",
    "Total Bedrooms",
    "View Y/N"
    
]
df = df[selected_columns]

check for duplicates

In [479]:
df.duplicated().sum()

40

In [480]:
df[df.duplicated()]

,Fireplace Y/N,Structure Type,Total Parking,New Construction,Air Conditioning Y/N,Heating Y/N,High School District,Waterfront Y/N,Senior Community Y/N,Virtual Tour,Carport Y/N,house_size,lot_size,Year Built,Total Baths,Longitude,Latitude,Property Condition,Total Bedrooms,View Y/N
758,Yes,House,2.0,No,Yes,Yes,Tacoma,No,No,Click here,No,"3,008 SQFT",0.26 Acres,1977,3,-122.430267,47.307781,NaN,5,Yes
944,No,House,2.0,No,Yes,Yes,Tacoma,No,No,NaN,No,"1,832 SQFT",0.23 Acres,1991,3,-122.409941,47.300871,NaN,4,Yes
953,Yes,House,2.0,No,No,Yes,Tacoma,No,No,NaN,No,"1,048 SQFT",0.23 Acres,1970,2,-122.400410,47.196295,NaN,4,NaN
968,Yes,House,1.0,No,No,Yes,Tacoma,No,No,Click here,No,"1,605 SQFT",0.14 Acres,1945,2,-122.491473,47.266188,NaN,4,NaN
1007,Yes,House,2.0,No,No,Yes,Clover Park,Yes,No,Click here,No,"3,239 SQFT",0.24 Acres,1968,3,-122.539840,47.163103,Very Good,4,Yes
1181,Yes,House,0.0,No,Yes,Yes,Tacoma,No,No,Click here,No,"1,032 SQFT",0.14 Acres,1945,1,-122.454259,47.211670,NaN,3,NaN
1225,Yes,House,1.0,No,No,Yes,Tacoma,No,No,Click here,No,"1,437 SQFT",0.20 Acres,1960,1,-122.503212,47.244594,Very Good,4,NaN
1359,Yes,House,0.0,No,Yes,Yes,Tacoma,No,No,Click here,No,"1,425 SQFT",0.05 Acres,1925,2,-122.458513,47.257834,Very Good,3,No
1384,Yes,House,10.0,No,Yes,Yes,Franklin Pierce,No,No,Click here,No,"3,294 SQFT",3.00 Acres,2009,3,-122.367091,47.142176,NaN,5,Yes
1406,Yes,House,0.0,No,No,Yes,Tacoma,No,No,Click here,No,"2,288 SQFT",0.18 Acres,1968,2,-122.487954,47.248507,NaN,4,NaN
1539,Yes,House,3.0,No,No,Yes,Tacoma,No,No,Click here,No,"2,366 SQFT",0.22 Acres,1990,3,-122.416335,47.303190,Very Good,3,NaN
1607,Yes,House,0.0,No,No,Yes,Tacoma,No,No,Click here,No,"2,064 SQFT",0.23 Acres,1948,2,-122.552146,47.242934,NaN,3,NaN
1907,Yes,House,5.0,No,Yes,Yes,Tacoma,No,No,Click here,No,"1,677 SQFT",0.23 Acres,1953,2,-122.508174,47.276351,NaN,3,Yes
1995,No,House,1.0,No,No,Yes,Tacoma,No,No,NaN,No,"2,020 SQFT",0.21 Acres,1955,2,-122.496966,47.251964,NaN,4,NaN
2133,No,House,0.0,No,Yes,Yes,Tacoma,No,No,NaN,No,800 SQFT,0.24 Acres,1920,2,-122.408185,47.227219,NaN,2,No
2330,Yes,House,2.0,No,No,Yes,Tacoma,No,No,NaN,No,"2,004 SQFT",0.16 Acres,2003,3,-122.496094,47.200519,Remodeled,3,NaN
2348,Yes,House,2.0,No,Yes,Yes,Franklin Pierce,No,Yes,Click here,No,"1,904 SQFT",0.11 Acres,2015,2,-122.399228,47.126112,NaN,3,Yes
2614,No,House,2.0,No,Yes,Yes,Tacoma,No,No,NaN,Yes,"1,160 SQFT",2.02 Acres,1933,2,-122.365438,47.169173,Remodeled,2,No
2693,Yes,House,2.0,No,No,Yes,Franklin Pierce,No,No,Click here,No,"1,056 SQFT",0.19 Acres,1951,2,-122.455173,47.165089,NaN,3,Yes
2732,Yes,House,1.0,No,No,Yes,Tacoma,No,No,NaN,No,"1,002 SQFT",0.13 Acres,1945,1,-122.491097,47.261570,Fair,2,Yes
2750,No,House,2.0,No,Yes,Yes,Tacoma,No,No,NaN,No,624 SQFT,0.21 Acres,1919,1,-122.492578,47.196889,NaN,2,No
2780,No,House,1.0,No,No,Yes,Franklin Pierce,No,No,NaN,No,845 SQFT,0.11 Acres,1950,1,-122.450568,47.152514,NaN,2,NaN
3030,Yes,House,2.0,No,No,Yes,Bethel,No,No,NaN,No,"2,202 SQFT",0.15 Acres,2003,3,-122.408828,47.113106,Very Good,4,NaN
3062,Yes,House,2.0,No,Yes,Yes,Tacoma,No,No,NaN,No,"1,780 SQFT",0.17 Acres,1979,2,-122.520744,47.284373,NaN,3,Yes
3118,No,House,2.0,No,No,Yes,Franklin Pierce,No,No,NaN,No,"1,677 SQFT",0.08 Acres,2010,3,-122.417638,47.149961,Good,4,NaN
3137,No,Manufactured House,0.0,No,Yes,Yes,Franklin Pierce,No,No,NaN,No,"1,682 SQFT",0.55 Acres,1984,2,-122.432401,47.146704,Very Good,3,NaN
3184,No,House,2.0,No,No,Yes,Bethel,No,No,Click here,No,"2,112 SQFT",0.43 Acres,2002,2,-122.371835,47.114556,Very Good,4,NaN
3223,Yes,House,2.0,No,Yes,Yes,Franklin Pierce,No,No,Click here,No,"1,794 SQFT",0.41 Acres,1959,2,-122.379266,47.140550,Good,3,NaN
3242,Yes,House,0.0,No,No,Yes,Tacoma,No,No,NaN,No,"1,348 SQFT",0.11 Acres,1921,1,-122.454394,47.229408,NaN,3,No
3362,Yes,House,1.0,No,No,Yes,Tacoma,No,No,NaN,No,"1,464 SQFT",0.13 Acres,1976,3,-122.498614,47.201638,NaN,3,NaN
3950,Yes,House,2.0,No,No,Yes,Tacoma,No,No,Click here,No,"1,571 SQFT",0.15 Acres,1952,2,-122.511396,47.270704,Remodeled,3,NaN
3995,No,House,2.0,No,No,Yes,Fife,No,No,Click here,No,866 SQFT,0.18 Acres,1944,1,-122.335718,47.261143,Good,2,Yes
4142,Yes,House,2.0,No,Yes,Yes,Franklin Pierce,No,No,NaN,No,"1,850 SQFT",0.97 Acres,1968,3,-122.366787,47.121441,NaN,3,NaN
4150,No,House,2.0,No,No,Yes,Tacoma,No,No,Click here,No,"1,080 SQFT",0.14 Acres,1910,1,-122.437108,47.202571,NaN,3,NaN
4177,Yes,House,1.0,No,Yes,Yes,Tacoma,No,No,NaN,No,"2,226 SQFT",0.12 Acres,1941,2,-122.493267,47.275097,NaN,4,NaN
4235,Yes,House,2.0,No,Yes,Yes,Tacoma,No,No,NaN,Yes,"1,394 SQFT",0.16 Acres,1950,1,-122.497653,47.253215,Good,2,No
4400,Yes,House,6.0,No,Yes,Yes,Tacoma,No,No,NaN,No,"4,233 SQFT",0.63 Acres,1981,3,-122.423992,47.312815,Remodeled,5,NaN
4404,Yes,House,1.0,No,Yes,Yes,Tacoma,No,No,Click here,No,"1,572 SQFT",0.19 Acres,1929,2,-122.398158,47.229230,Updated/Remodeled,3,NaN
4473,No,House,1.0,No,Yes,Yes,Tacoma,No,No,Click here,No,764 SQFT,0.14 Acres,1920,1,-122.497260,47.254236,Very Good,2,NaN
4495,Yes,House,3.0,No,Yes,Yes,Fife,No,No,Click here,No,"3,688 SQFT",0.38 Acres,2015,4,-122.346022,47.264263,Very Good,4,NaN

In [481]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

Deleting the missing values from variables using case deletion

In [482]:
df.dropna(subset=["Fireplace Y/N", 
                  "Structure Type", 
                  "Total Parking", 
                  "New Construction", 
                  "Air Conditioning Y/N",
                  "Heating Y/N",
                  "High School District",
                  "Waterfront Y/N",
                  "Senior Community Y/N"
                 ], inplace = True)

Impute values to missing values in View Y/N, Property Condition and Virtual Tour

In [483]:
df["View Y/N"] = df["View Y/N"].fillna("Unknown")
df["Property Condition"] = df["Property Condition"].fillna("Unknown")
df["Virtual Tour"] = df["Virtual Tour"].fillna("No")

df["Virtual Tour"] = df["Virtual Tour"].str.replace("Click here", "Yes")

Encoding categorical variables

In [484]:

Binary_columns = [
    "Fireplace Y/N", 
    "Air Conditioning Y/N",
    "Heating Y/N",
    "Waterfront Y/N",
    "Senior Community Y/N",
    "View Y/N",
    "Virtual Tour",
    "Carport Y/N"
]

for col in Binary_columns:
    df[col] = df[col].map({
        "Yes": 1,
        "No": 0,
        "Unknown": 2
    })

In [485]:
df[["Fireplace Y/N", 
    "Air Conditioning Y/N",
    "Heating Y/N",
    "Waterfront Y/N",
    "Senior Community Y/N",
    "View Y/N", 
    "Virtual Tour",
    "Carport Y/N"
   ]]

,Fireplace Y/N,Air Conditioning Y/N,Heating Y/N,Waterfront Y/N,Senior Community Y/N,View Y/N,Virtual Tour,Carport Y/N
0,0,0,1,0,0,0,0,0
1,1,0,1,0,0,1,1,0
2,1,1,1,0,0,2,0,0
3,1,0,1,0,0,2,1,0
4,0,0,1,0,0,2,0,0
...,...,...,...,...,...,...,...,...
4504,1,1,1,0,0,1,1,1
4505,1,0,1,0,0,2,1,0
4506,0,0,1,0,0,0,0,0
4507,1,0,1,0,0,2,0,0
4508,1,1,1,0,0,1,1,0

standardized property condition variable

In [486]:
df["Property Condition"].unique()

array(['Unknown', 'Very Good', 'Good', 'Under Construction',
       'Updated/Remodeled', 'Remodeled', 'Fixer', 'Average', 'Fair',
       'Restored'], dtype=object)

In [487]:
df["Property Condition"] = df["Property Condition"].map({
    "Updated/Remodeled": "Remodeled",
    "Fixer": "Fixer",
    "Remodeled": "Remodeled",
    "Average": "Average",
    "Fair": "Fair",
    "Restored": "Restored",
    "Very Good": "Very Good",
    "Good": "Good",
    "Under Construction": "Under Construction",
    "Unknown": "Unknown"
})
df["Property Condition"].unique()

array(['Unknown', 'Very Good', 'Good', 'Under Construction', 'Remodeled',
       'Fixer', 'Average', 'Fair', 'Restored'], dtype=object)

standardizing units of house_size and lot_size

In [488]:
df["house_size"]

0         800 SQFT
1       1,944 SQFT
2       1,916 SQFT
3       1,436 SQFT
4         951 SQFT
           ...
4504    1,536 SQFT
4505    2,134 SQFT
4506    1,902 SQFT
4507    1,800 SQFT
4508    3,601 SQFT
Name: house_size, Length: 4239, dtype: object

In [489]:
df["house_size"] = df["house_size"].str.replace("SQFT", "").str.replace(",", "").astype("float")
df["house_size"]

0        800.0
1       1944.0
2       1916.0
3       1436.0
4        951.0
         ...
4504    1536.0
4505    2134.0
4506    1902.0
4507    1800.0
4508    3601.0
Name: house_size, Length: 4239, dtype: float64

In [490]:
df["lot_size"]

0       0.48 Acres
1       0.23 Acres
2       0.14 Acres
3       0.13 Acres
4       0.15 Acres
           ...
4504    0.30 Acres
4505    0.18 Acres
4506    0.13 Acres
4507    0.15 Acres
4508    0.48 Acres
Name: lot_size, Length: 4239, dtype: object

In [491]:
ACRE_TO_SQFT = 43560

lot_multiplier = df["lot_size"].str.contains("Acres").map(
    lambda x: ACRE_TO_SQFT if x else 1
)

df["lot_size"] = df["lot_size"].str.replace("Acres", "").astype("float")*lot_multiplier

df["lot_size"].describe()

count      4239.000000
mean      10718.082378
std       23455.642702
min           0.000000
25%        5227.200000
50%        6534.000000
75%        9147.600000
max      653400.000000
Name: lot_size, dtype: float64

In [492]:
df["lot_size"].describe()

count      4239.000000
mean      10718.082378
std       23455.642702
min           0.000000
25%        5227.200000
50%        6534.000000
75%        9147.600000
max      653400.000000
Name: lot_size, dtype: float64

In [493]:
df.isnull().sum()

Fireplace Y/N           0
Structure Type          0
Total Parking           0
New Construction        0
Air Conditioning Y/N    0
Heating Y/N             0
High School District    0
Waterfront Y/N          0
Senior Community Y/N    0
Virtual Tour            0
Carport Y/N             0
house_size              0
lot_size                0
Year Built              0
Total Baths             0
Longitude               0
Latitude                0
Property Condition      0
Total Bedrooms          0
View Y/N                0
dtype: int64

In [494]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4239 entries, 0 to 4508
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Fireplace Y/N         4239 non-null   int64
 1   Structure Type        4239 non-null   object
 2   Total Parking         4239 non-null   float64
 3   New Construction      4239 non-null   object
 4   Air Conditioning Y/N  4239 non-null   int64
 5   Heating Y/N           4239 non-null   int64
 6   High School District  4239 non-null   object
 7   Waterfront Y/N        4239 non-null   int64
 8   Senior Community Y/N  4239 non-null   int64
 9   Virtual Tour          4239 non-null   int64
 10  Carport Y/N           4239 non-null   int64
 11  house_size            4239 non-null   float64
 12  lot_size              4239 non-null   float64
 13  Year Built            4239 non-null   int64
 14  Total Baths           4239 non-null   int64
 15  Longitude             4239 non-null   float64
 16  Latitude              4239 non-null   float64
 17  Property Condition    4239 non-null   object
 18  Total Bedrooms        4239 non-null   int64
 19  View Y/N              4239 non-null   int64
dtypes: float64(5), int64(11), object(4)
memory usage: 695.5+ KB